feat: change docker build trigger and tags
catenax-ng/gh-org-checks pull request #8
Opened 2023-01-12 13:53 UTC by almadigabor

- Trigger on push to main branch and semver tag
- Add multiple tags to the image

2023-01-12 14:18 UTC, carslen requested changes

2023-01-12 14:18 UTC, carslen commented on .github/workflows/docker-build.yaml
> +      - 'v*'
I would suggest to use `v*.*.*` instead, to enforce real semver tags. Otherwise a pushed tag `v1` would be valid. See also our [golden path repo](https://github.com/catenax-ng/k8s-helm-example/blob/main/.github/workflows/docker-build.yaml#L8)

2023-01-12 15:04 UTC, almadigabor commented on .github/workflows/docker-build.yaml
> +      - 'v*'
Right, I've implemented this. Also I was wondering if we should use full semver regex in some situations: 
`^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`

2023-01-16 08:14 UTC, carslen approved these changes
LGTM

2023-01-16 08:16 UTC, merged